project_id = "hunwnggzidopjhovvika"

[functions.send-to-slack]
verify_jwt = false

[functions.slack-events]
verify_jwt = false

[functions.reset-password]
verify_jwt = false

[functions.channel-talk-app]
verify_jwt = false

[functions.sync-order-to-channel-talk]
verify_jwt = false
